name: CI_SECRETS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
          node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run app
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        node server.js
